### ISSUE TITLE
[CES] UAT Feedback changes-2

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/CES#20]
https://docs.google.com/spreadsheets/d/1C1YvvEo9MUyCuK6pRiuqBLTDJ3SnGfF_uVRHMczrdWc/edit#gid=155957619

**Comment by garimadosar5** [comment]
QA Notes - 
- If I edit any visit, it creates a new visit. **Yes, it will create a new visit based on the new choices. We are giving cancel option to cancel the earlier visits generated due to wrong choice**
- Feedback row 34, still working the same way. as given in the case: Sashank Rawat. 
2nd case - Rahul Dubey. **Its working as required. We can discuss this on call**
- Feedback row 38. now after visit "Test result screening", any visit is not getting scheduled. Case - Akhil Sen. **Fixed**
- Feedback Row 40, after "Test result for screening" visit, no visit is getting scheduled. Case - Nandini Patil.
- **Fixed**
